[package]
name = "urlkurztacean"
version = "0.1.0"
edition = "2024"

[lib]
name = "urlkurztacean"
path = "src/lib/lib.rs"

[dependencies]
anyhow = "1.0.100"
rand = "0.9.2"
thiserror = "2.0.17"
tokio = "1.48.0"
url = "2.5.7"
